# Generated by Django 3.0.6 on 2020-06-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=100)),
                ('textcontent', models.TextField()),
                ('imgcontent', models.ImageField(upload_to='')),
                ('Filecontent', models.FileField(upload_to='')),
            ],
        ),
    ]
