# Generated by Django 3.0.6 on 2020-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_auto_20200628_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='Filecontent',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='imgcontent',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='textcontent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
