# Generated by Django 3.0.6 on 2020-06-29 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_auto_20200628_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='Filecontent',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='imgcontent',
        ),
    ]
