# Generated by Django 3.0.6 on 2020-06-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postcontent',
        ),
    ]
