# Generated by Django 3.0.6 on 2020-06-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0007_remove_post_postcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='postcontent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='postcontentfile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='postcontentimg',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
