# Generated by Django 3.0.6 on 2020-07-01 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0008_auto_20200628_2208'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
