# Generated by Django 3.0.6 on 2020-07-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0010_auto_20200702_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='standard',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
