# Generated by Django 3.0.6 on 2020-07-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0011_auto_20200702_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='Filename',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
